### PR TITLE
Update function ip

### PR DESCRIPTION
**Pull request by rainbow-hue**
ipinfo has been giving issues so updated the function to curl https://whatismyip.akamai.com

### CODE REVIEW

**Comment by abdullahdevrel** [comment]
Hmmmm... I think we do not block TOR IPs. Also, you should use the `/ip` endpoint as it directly provides the IP address. Can you take a look, please?

```
ipinfo.io/ip
```

**Comment by rainbow-hue** [comment]
ipinfo.io blocks TOR IPs. I have attached screenshot for reference.

Screenshot 2024-12-16 151203

**Comment by abdullahdevrel** [comment]
Hmm, that is interesting. Okay, let me talk to our engineers. There is a non-zero chance it is a bug.

**Comment by rainbow-hue** [comment]
when i try to curl google.com, it redirects to a captacha page. 
previously, when using ipinfo.io to get the ip it used to give out the ip one or two times and then block altogether, but now it just shows a 403 forbidden page all the time.

**Comment by abdullahdevrel** [comment]
That is very unfortunate. I confirmed with our engineering team that we do not block TOR IPs. GCP itself is blocking some TOR IPs, which impacts us as we are hosted on their platform.

**Comment by Und3rf10w** [comment]
I'll research alternatives. I'm not 100% sold on Akamai.

One thing I want to keep in mind is how the ip info data is used, or could potentially be used. In theory, an IP info service could (theoretically) be used to collect intelligence on kali-anonsurf users, which is something I have front-of-mind. I understand this is also technically a risk with ipinfo.

One of the things I LIKE about the GCP block on the ipinfo.io service, aside from ease-of-use, is the fact that when GCP blocks that IP, I know I should avoid that, and will typically add that IP or range to `ExcludeExitNodes` in torrc.

**Comment by abdullahdevrel** [comment]
Thank you very much for your careful review. 

We processed around 2 trillion requests in 2023, and the `ipinfo.io/ip` endpoint likely receives tens (if not hundreds) of billions of requests each day. It is impossible to gather any information on your users from a simple API call that returns a public IP address.

I wish we had the capability to do something about how GCP handles IP geolocation on their infrastructure. They are clearly mistaken, as the IP @rainbow-hue shared is a Tor Exit Node based in the Netherlands with a well-known ASN among TOR users. However, Google incorrectly identifies it as being in Iran. That is because of their "device-based IP geolocation" method while we use the ping triangulation method. Their method is prone to mistaking VPNs, Proxy, and Tor IPs on the user location instead of the server location quite frequently because of that.

It is a very unfortunate situation. The issue is that very few companies want to open their services to TOR exit IPs, but we are happy to support TOR users as well.

**Comment by Und3rf10w** [comment]
@abdullahdevrel, thank you for your detailed response and for taking the time to engage with this. Your transparency and willingness to collaborate demonstrate the values I prioritize in the services I choose for this project.

As the maintainer of this project, my immediate responsibility is to the users who trust this tool to safeguard their privacy and security. Every decision I opt to make is guided by a commitment to uphold that trust. IPinfo was selected after careful evaluation of its reliability, security practices, volume, and alignment with my values. Your engagement here strengthens my confidence in this decision, especially considering the substantial data volume IPinfo handles, which was a significant factor in my choice.

While I previously mentioned some theoretical risks, my intention was to convey my dedication to thoroughly evaluating all potential outcomes when selecting IP address providers. I want to emphasize that my remarks were not meant to suggest that IPinfo, or any provider, acts with harmful intent. Instead, I aim to ensure that the services I rely on adhere to the transparency, security, and privacy principles that are foundational to this project.

I also recognize the unique challenges of supporting privacy-focused tools like TOR, particularly when dealing with infrastructure policies or platform-level restrictions. In my mind, these challenges are not exclusive to IPinfo but reflect the broader complexities of building tools that prioritize user privacy. I appreciate IPinfo’s efforts to navigate these challenges and support projects like this. As I mentioned, I do not necessarily view GCP's implicit block of known TOR IP addresses as negative, particularly for this project, and in practice, it may actually benefit the users of `kali-anonsurf` depending on their priorities.

To the users of `kali-anonsurf`: Your privacy and security remain my highest priority. While no solution is entirely without risk, I am committed to making decisions that reflect your trust in this project and to continually assess the services integrated to ensure they meet your expectations.

Thank you again for your valuable input and for helping to clarify this situation. Open dialogue and collaboration are essential to the continued improvement and security of this project. I look forward to working with IPinfo and the broader community to maintain the highest standards for `kali-anonsurf` users.

**Comment by abdullahdevrel** [comment]
Thank you very much @Und3rf10w. We are present and available to help in anyway possible and answer any questions you might have. Really appreciate talking with you.

**Comment by Und3rf10w** [comment]
I'm gonna switch to [ipify](https://www.ipify.org/) for now. They are open source, serve a high volume of requests, and generally shouldn't block TOR addresses.

In addition, I've added a `RISKY` tag to the `myip` command to communicate that there is risk associated with that function.

**Pull request merged**
